version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - npm install
     - npm run build
 post_build:
   commands:
     - echo "post_build step"
     - aws s3 sync --delete dist/. "s3://baladigitalcloud-static-site1-vu.baladigitalcloud.com"
